### ISSUE TITLE
OSError: [Errno 38] Function not implemented

### ISSUE THREAD

**Issue by newmindJP** [linuxserver/docker-openvpn-as#58]
I did fresh install with docker-compose - got following error (endless list with always the same error - cust copied the last one ...) - based on some search per google this is maybe a python bug.  Does the latest version run somewhere?

```
openvpn-as    | Traceback (most recent call last):
openvpn-as    |   File "<string>", line 1, in <module>
openvpn-as    |   File "build/bdist.linux-x86_64/egg/pyovpn/sagent/sagent_entry.py", line 17, in openvpnas
openvpn-as    |   File "build/bdist.linux-x86_64/egg/pyovpn/util/mycprof.py", line 2, in run_cprofile
openvpn-as    |   File "build/bdist.linux-x86_64/egg/pyovpn/util/env.py", line 7, in <module>
openvpn-as    |   File "build/bdist.linux-x86_64/egg/pyovpn/util/valid.py", line 3, in <module>
openvpn-as    |   File "build/bdist.linux-x86_64/egg/pyovpn/util/error.py", line 4, in <module>
openvpn-as    |   File "/config/lib/python2.7/xmlrpclib.py", line 145, in <module>
openvpn-as    |     import httplib
openvpn-as    |   File "/config/lib/python2.7/httplib.py", line 80, in <module>
openvpn-as    |     import mimetools
openvpn-as    |   File "/config/lib/python2.7/mimetools.py", line 6, in <module>
openvpn-as    |     import tempfile
openvpn-as    |   File "/config/lib/python2.7/tempfile.py", line 35, in <module>
openvpn-as    |     from random import Random as _Random
openvpn-as    |   File "/config/lib/python2.7/random.py", line 885, in <module>
openvpn-as    |     _inst = Random()
openvpn-as    |   File "/config/lib/python2.7/random.py", line 97, in __init__
openvpn-as    |     self.seed(x)
openvpn-as    |   File "/config/lib/python2.7/random.py", line 113, in seed
openvpn-as    |     a = long(_hexlify(_urandom(2500)), 16)
openvpn-as    | OSError: [Errno 38] Function not implemented

```

**Comment by aptalca** [comment]
runs fine here. Post your compose yml

**Comment by Mr-Clear** [comment]
Same here. I just call the example command:
```
docker create \
  --name=openvpn-as \
  --cap-add=NET_ADMIN \
  -e PUID=995 \
  -e PGID=994 \
  -e TZ=Europe/London \
  -e INTERFACE=eth0 \
  -p 943:943 \
  -p 9443:9443 \
  -p 1194:1194/udp \
  -v /docker/vpn/data2:/config \
  --restart unless-stopped \
  linuxserver/openvpn-as

docker start openvpn-as
```

Log output:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    995
User gid:    994
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-time: executing...

Current default time zone: 'Europe/London'
Local time is now:      Tue Feb 19 19:34:56 GMT 2019.
Universal Time is now:  Tue Feb 19 19:34:56 UTC 2019.

[cont-init.d] 20-time: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-openvpn-init: executing...
Traceback (most recent call last):
  File "/config/bin/_ovpn-init", line 7, in <module>
    from pyovpn.net.net import NetInfoLinux
  File "build/bdist.linux-x86_64/egg/pyovpn/net/net.py", line 12, in <module>
  File "build/bdist.linux-x86_64/egg/pyovpn/util/error.py", line 4, in <module>
  File "/usr/local/openvpn_as/lib/python2.7/xmlrpclib.py", line 145, in <module>
    import httplib
  File "/usr/local/openvpn_as/lib/python2.7/httplib.py", line 80, in <module>
    import mimetools
  File "/usr/local/openvpn_as/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/usr/local/openvpn_as/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "/usr/local/openvpn_as/lib/python2.7/random.py", line 885, in <module>
    _inst = Random()
  File "/usr/local/openvpn_as/lib/python2.7/random.py", line 97, in __init__
    self.seed(x)
  File "/usr/local/openvpn_as/lib/python2.7/random.py", line 113, in seed
    a = long(_hexlify(_urandom(2500)), 16)
OSError: [Errno 38] Function not implemented
[cont-init.d] 40-openvpn-init: exited 0.
[cont-init.d] 50-interface: executing...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pyovpn/sagent/sagent_entry.py", line 37, in confdba
  File "build/bdist.linux-x86_64/egg/pyovpn/db/confdb_admin.py", line 6, in <module>
  File "build/bdist.linux-x86_64/egg/pyovpn/util/error.py", line 4, in <module>
  File "/config/lib/python2.7/xmlrpclib.py", line 145, in <module>
    import httplib
  File "/config/lib/python2.7/httplib.py", line 80, in <module>
    import mimetools
  File "/config/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/config/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "/config/lib/python2.7/random.py", line 885, in <module>
    _inst = Random()
  File "/config/lib/python2.7/random.py", line 97, in __init__
    self.seed(x)
  File "/config/lib/python2.7/random.py", line 113, in seed
    a = long(_hexlify(_urandom(2500)), 16)
OSError: [Errno 38] Function not implemented
```

**Comment by aptalca** [comment]
What is your host os?
Synology?

I cannot reproduce this and tried on multiple different systems

**Comment by savageautomate** [comment]
Same repeated error/issue here. (error log below).

It seems to have this issue starting with build/tag: `2.6.1-ls2`
(Build/tag `169` works fine.)
https://hub.docker.com/r/linuxserver/openvpn-as/tags

Coincidentally the Docker image size dropped from 96MB to 84MB between these two builds.  
_(I have not compared them yet.)_

#### Host OS:
Ubuntu 14.04.5 LTS  _(I know its outdated, its just a test machine -- could this perhaps be the issue?)_ 

#### Docker Version:
`Docker version 18.06.1-ce, build e68fc7a`

#### Docker command:
```
sudo docker run --detach \
     --name=openvpn-as \
     -e PUID=1001 \
     -e PGID=1001 \
     -e TZ=America/New_York \
     -e INTERFACE=eth0  \
     --net=host \
     --privileged \
     -v /etc/openvpn-as/config:/config \
     --restart unless-stopped \
     linuxserver/openvpn-as:2.6.1-ls2
```

#### OpenVPN AS Log:

```
s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
We gratefully accept donations at:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1001,
User gid:    1001,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 20-time: executing... ,
,
Current default time zone: 'America/New_York',
Local time is now:      Wed Feb 20 14:24:31 EST 2019.,
Universal Time is now:  Wed Feb 20 19:24:31 UTC 2019.,
,
[cont-init.d] 20-time: exited 0.,
[cont-init.d] 30-config: executing... ,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] 40-openvpn-init: executing... ,
[cont-init.d] 40-openvpn-init: exited 0.,
[cont-init.d] 50-interface: executing... ,
Traceback (most recent call last):,
  File "<string>", line 1, in <module>,
  File "build/bdist.linux-x86_64/egg/pyovpn/sagent/sagent_entry.py", line 37, in confdba,
  File "build/bdist.linux-x86_64/egg/pyovpn/db/confdb_admin.py", line 6, in <module>,
  File "build/bdist.linux-x86_64/egg/pyovpn/util/error.py", line 4, in <module>,
  File "/config/lib/python2.7/xmlrpclib.py", line 145, in <module>,
    import httplib,
  File "/config/lib/python2.7/httplib.py", line 80, in <module>,
    import mimetools,
  File "/config/lib/python2.7/mimetools.py", line 6, in <module>,
    import tempfile,
  File "/config/lib/python2.7/tempfile.py", line 35, in <module>,
    from random import Random as _Random,
  File "/config/lib/python2.7/random.py", line 885, in <module>,
    _inst = Random(),
  File "/config/lib/python2.7/random.py", line 97, in __init__,
    self.seed(x),
  File "/config/lib/python2.7/random.py", line 113, in seed,
    a = long(_hexlify(_urandom(2500)), 16),
OSError: [Errno 38] Function not implemented,
```

**Comment by thelamer** [comment]
You are running host networking, do you have an eth0 host level?

**Comment by savageautomate** [comment]
@thelamer 

**Yes.**  _(MAC address masked below)_
And the VPN server is fully working using build/tag `169`.

```
$ ifconfig eth0
eth0      Link encap:Ethernet  HWaddr [-REDACTED-] 
          inet addr:10.1.1.17  Bcast:10.1.255.255  Mask:255.255.0.0
          inet6 addr: [-REDACTED-]/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:183899387 errors:0 dropped:0 overruns:0 frame:0
          TX packets:160769708 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:60351046293 (60.3 GB)  TX bytes:129640462931 (129.6 GB)
```

**Comment by aptalca** [comment]
Can you guys test this image tag to see if it works?
`lsiodev/openvpn-as:2.6.1-pkg-d78f8cab-dev-a7f19ca11deda9d316853a358ff39e4d56952f25`

so replace `linuxserver/openvpn-as` in your docker run/ compose with the above

**Comment by savageautomate** [comment]
@aptalca ,

Yes, that image tag is working:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
We gratefully accept donations at:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1001,
User gid:    1001,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 20-time: executing... ,
,
Current default time zone: 'America/New_York',
Local time is now:      Thu Feb 21 11:42:41 EST 2019.,
Universal Time is now:  Thu Feb 21 16:42:41 UTC 2019.,
,
[cont-init.d] 20-time: exited 0.,
[cont-init.d] 30-config: executing... ,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] 40-openvpn-init: executing... ,
[cont-init.d] 40-openvpn-init: exited 0.,
[cont-init.d] 50-interface: executing... ,
MOD Default {} {},
MOD Default {} {},
MOD Default {} {},
MOD Default {} {},
[cont-init.d] 50-interface: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
```
Thanks

**Comment by aptalca** [comment]
The only difference is the main branch os on bionic and uses the bionic package from openvpn. This tag uses xenial package on xenial base

**Comment by savageautomate** [comment]
@aptalca 

I just installed `linuxserver/openvpn-as:latest` on an Ubuntu 18.04.1 LTS host system and its working fine as well.   So I guess the host OS has some dependency related issue? 

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

$ docker -v
Docker version 18.09.2, build 6247962
```
